title: Christina Vu
logo: "/images/logo.png?raw=true"
description:
  <a href="https://www.linkedin.com/[removed]" rel="nofollow noreferrer">
    <img src="https://i.sstatic.net/gVE0j.png" alt="linkedin"> LinkedIn
  </a> &nbsp; 
  <a href="https://github.com/[removed]" rel="nofollow noreferrer">
    <img src="https://i.sstatic.net/tskMh.png" alt="github"> Github
  </a>


remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
